### ISSUE TITLE
Bug report for Open Vision 10.2

### ISSUE THREAD

**Issue by MasterRoCcO** [OpenVisionE2/openvision-development-platform#70]
**Open Vision revision**
Tell us it's OV 10.2-r246?

**STB vuduo4kse**

I did this about 5 minutes ago.
git clone --depth 1 https://github.com/OpenVisionE2/openvision-development-platform.git

And wanted to build an image for the vuduo4kse. But I'll make this mistake right from the start.

Building image for vuduo4kse
WARNING: Layer meta-openvision-layer should set LAYERSERIES_COMPAT_meta-openvision-layer in its conf/layer.conf file to list the core layer names it is compatible with.
Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:04
Loaded 5157 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:10
Parsing of 4053 .bb files complete (3657 cached, 396 parsed). 5557 targets, 1002 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'libvugles2-vuduo4kse' (but /home/bot/server1/openvision-development-platform/meta-openvision/recipes-openvision/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'libvugles2-vuduo4kse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libvugles2-vuduo4kse']
ERROR: Required build target 'openvision-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-image', 'enigma2', 'libvugles2-vuduo4kse']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Fehler 1
bot@s10925715:~/server1/openvision-development-platform$

Danach habe ich zum Test noch versucht ein Image für die vuzero4k zubauen, da läufter gleich an ohne Fehler.

**Comment by persianpros** [comment]
Try again now, is vuduo4kse out?

**Comment by MasterRoCcO** [comment]
Well, I've done ./update.sh. And again I need to build a picture for the vuduo4kse. There is always a mistake at the beginning.

Building image for vuduo4kse
WARNING: Layer meta-openvision-layer should set LAYERSERIES_COMPAT_meta-openvision-layer in its conf/layer.conf file to list the core layer names it is compatible with.
Loading cache: 100% |#########################################################################################################################################################| Time: 0:00:02
Loaded 5157 entries from dependency cache.
Parsing recipes: 100% |#######################################################################################################################################################| Time: 0:00:11
Parsing of 4053 .bb files complete (3657 cached, 396 parsed). 5557 targets, 1002 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
**ERROR: Nothing RPROVIDES 'libvugles2-vuduo4kse' (but /home/bot/server1/openvision-development-platform/meta-openvision/recipes-openvision/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'libvugles2-vuduo4kse' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libvugles2-vuduo4kse']
ERROR: Required build target 'openvision-enigma2-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-image', 'enigma2', 'libvugles2-vuduo4kse']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:99: image] Fehler 1**
bot@s10925715:~/server1/openvision-development-platform$

**Comment by persianpros** [comment]
Seems your OE isn't up-to-date, cd to openvision-development-platform and enter:

```
git reset --hard HEAD~10
./update.sh
```

**Comment by MasterRoCcO** [comment]
Even if I read it in from scratch (renamed the old dir).
And now he says to me to build an image for the vuduo4kse, I still get the same error.

So I made mv openvision-development-platform openvision-development-platform1
then
git clone --depth 1 https://github.com/OpenVisionE2/openvision-development-platform.git
cd / home / bot / server1 / openvision-development-platform

IMAGECMD = 'make image feed'
export MACHINE = vuduo4kse; $ IMAGECMD
And as I said, the same mistake comes

**Comment by persianpros** [comment]
There was a mistake I saw it just now, try image.sh now.

**Comment by MasterRoCcO** [comment]
Thanks, now it works, now he starts building the picture. Hence it can be closed here

**Comment by MasterRoCcO** [comment]
I won't get the box until Saturday, but then I'll post the pictures

**Comment by MasterRoCcO** [comment]
Sorry but the image doesn't finish!

Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:04
Loaded 5158 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:19
Parsing of 4054 .bb files complete (3658 cached, 396 parsed). 5558 targets, 1002 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python-python' (but /home/bot/server1/openvision-development-platform/meta-openvision/recipes-connectivity/sabnzbd/sabnzbd_2.3.7.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python-python']
ERROR: Required build target 'openvision-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-feed', 'sabnzbd', 'python-python']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:103: feed] Fehler 1

**Comment by persianpros** [comment]
Should be ok now but if you're building the feed for this model it's a wrong thing to do.

**Comment by MasterRoCcO** [comment]
OK thank you for the info

have now made cd / home / bot / server1 / openvision-development-platform && ./update.sh and again IMAGECMD = 'make image feed' export MACHINE = vuduo4kse; $ IMAGECMD


Or is it better to start all over again

**Comment by MasterRoCcO** [comment]
ERROR: Nothing RPROVIDES '{@bb.utils.contains("PYTHONEXACTVERSION",' (but /home/bot/server1/openvision-development-platform/meta-openvision/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-xstreamity.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '{@bb.utils.contains("PYTHONEXACTVERSION",' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['{@bb.utils.contains("PYTHONEXACTVERSION",']
ERROR: Required build target 'openvision-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-feed', 'enigma2-plugin-extensions-xstreamity', '{@bb.utils.contains("PYTHONEXACTVERSION",']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:103: feed] Fehler 1
bot@s10925715:~/server1/openvision-development-platform$

**Comment by persianpros** [comment]
The way you work with Open Vision is just not the way we do things and that's why you get strange erros, just cd to openvision-development-platform:

```
./image.sh
Specific
Vision
vuduo4kse
```

when you get the image then go for the feed!

**Comment by MasterRoCcO** [comment]
OK with because as you say it goes through !! So my friend gave me half-wrong orders.

The image is built! But that happens with the feed

-e Done!

Bereits aktuell.

-e Done.
-e
-e Updated.
-e
-e Compiling Specific images, please wait ...
-e
-e Do you want to set your own feed?
-e
-e Answers are in green:
-e
-e Yes - No
-e
-e Enter custom feed mode:
-e
No
-e
-e Enter your specific machine name exactly like what you see in Vision-metas.md
-e
vuduo4kse
-e
-e Compiling vuduo4kse image, please wait ...
-e
Generating /home/bot/server1/openvision-development-platform/build/conf/openvision.conf
Generating /home/bot/server1/openvision-development-platform/build/conf/local.conf
Building feed for vuduo4kse
WARNING: Layer meta-openvision-layer should set LAYERSERIES_COMPAT_meta-openvision-layer in its conf/layer.conf file to list the core layer names it is compatible with.
Loading cache: 100% |##########################################################################################################################################################################################################| Time: 0:00:01
Loaded 5158 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################################################################################################################| Time: 0:00:12
Parsing of 4054 .bb files complete (3658 cached, 396 parsed). 5558 targets, 1002 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES '"python-imaging' (but /home/bot/server1/openvision-development-platform/meta-openvision/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-xstreamity.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '"python-imaging' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['"python-imaging']
ERROR: Required build target 'openvision-enigma2-feed' has no buildable providers.
Missing or unbuildable dependency chain was: ['openvision-enigma2-feed', 'enigma2-plugin-extensions-xstreamity', '"python-imaging']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:103: feed] Fehler 1
-e
-e Done, the compiled image is in build/tmp/deploy/images/vuduo4ksevuduo4kse folder!
-e It's a zipped file like openvision-enigma2-develop-english|multilanguage|extralanguage-10-r246-vuduo4ksevuduo4kse.zip
bot@s10925715:~/server1/openvision-development-platform$

**Comment by persianpros** [comment]
Should be ok now :+1: 

P.S. when you compiled the image please share it on https://www.linuxsat-support.com too so the rest could use and test it :+1:

**Comment by MasterRoCcO** [comment]
should I post that there?

https://www.linuxsat-support.com/board/1616-vu-duo-4k-se/

**Comment by persianpros** [comment]
Yes thank you :+1:

**Comment by MasterRoCcO** [comment]
So the feed is currently being built !! When it runs through, I'll upload the image there! But now I have a very short question!

How can I remove this
WARNING: Layer meta-openvision-layer should set LAYERSERIES_COMPAT_meta-openvision-layer in its conf / layer.conf file to list the core layer names it is compatible with.

**Comment by persianpros** [comment]
For now just compile the image/feed but don't publish it as it won't boot.

Recent enigma2 changes made it unbootable so wait for my green light.

**Comment by MasterRoCcO** [comment]
ok
https://www.linuxsat-support.com/thread/145249-open-vision-10-2-new-master-branch-of-oe-bitbake-1-48-on-ubuntu-20-04-x-lts-gcc/

**Comment by persianpros** [comment]
Ok r248 should be fine, run image.sh again (no need to remove anything) :+1:

**Comment by MasterRoCcO** [comment]
So now have the box here and first put the r246 on it. But the box does not boot. So I don't need to test r249 on the Duo4kse for now.

**Comment by persianpros** [comment]
Actually you need to test a new version as some problems fixed in r248 and now only thing could make boot problems is FCC commit.

**Comment by MasterRoCcO** [comment]
ok i'm just building the r249 and get in touch again

**Comment by MasterRoCcO** [comment]
First of all, here is some general information about FCC in the original image http://code.vuplus.com/download/boximages/30/vuduo4kse/vuplus-image-vuduo4kse-20201020155435_usb.zip, FCC is also included.

I have now made the r249, it still does not boot. So there is still an error in the build.

So I will now build an image for the vuultimo4k to boot and test FCC

**Comment by persianpros** [comment]
Regarding the boot problem I need some logs, see: https://forum.openvision.tech/viewtopic.php?f=15&t=446

**Comment by MasterRoCcO** [comment]
I can't even connect the stb it is not found in the network

**Comment by persianpros** [comment]
Hmm so LAN isn't working?

**Comment by MasterRoCcO** [comment]
no, not possible, only the power button and + and - light up. otherwise everything is dead

**Comment by persianpros** [comment]
Hmm this is weird as we never had such problem with Vu+ maybe something isn't correct in our sources and get copied from the normal model not SE.

**Comment by MasterRoCcO** [comment]
What can I do that you get the information you need! E.g. VTI image on it and make a few logs from the HW

**Comment by persianpros** [comment]
@MasterRoCcO 

Please compile a new image for vuduo4kse but without changing the defconfig or anything.
